// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: import1.proto

package import1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TestImport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRun string `protobuf:"bytes,1,opt,name=is_run,json=isRun,proto3" json:"is_run,omitempty"`
	IsGo  string `protobuf:"bytes,2,opt,name=is_go,json=isGo,proto3" json:"is_go,omitempty"`
}

func (x *TestImport) Reset() {
	*x = TestImport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestImport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestImport) ProtoMessage() {}

func (x *TestImport) ProtoReflect() protoreflect.Message {
	mi := &file_import1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestImport.ProtoReflect.Descriptor instead.
func (*TestImport) Descriptor() ([]byte, []int) {
	return file_import1_proto_rawDescGZIP(), []int{0}
}

func (x *TestImport) GetIsRun() string {
	if x != nil {
		return x.IsRun
	}
	return ""
}

func (x *TestImport) GetIsGo() string {
	if x != nil {
		return x.IsGo
	}
	return ""
}

var File_import1_proto protoreflect.FileDescriptor

var file_import1_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x38, 0x0a, 0x0a, 0x54, 0x65, 0x73, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x69, 0x73, 0x5f, 0x72, 0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x73, 0x52, 0x75, 0x6e, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x67, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x47, 0x6f, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_import1_proto_rawDescOnce sync.Once
	file_import1_proto_rawDescData = file_import1_proto_rawDesc
)

func file_import1_proto_rawDescGZIP() []byte {
	file_import1_proto_rawDescOnce.Do(func() {
		file_import1_proto_rawDescData = protoimpl.X.CompressGZIP(file_import1_proto_rawDescData)
	})
	return file_import1_proto_rawDescData
}

var file_import1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_import1_proto_goTypes = []interface{}{
	(*TestImport)(nil), // 0: TestImport
}
var file_import1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_import1_proto_init() }
func file_import1_proto_init() {
	if File_import1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_import1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestImport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_import1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_import1_proto_goTypes,
		DependencyIndexes: file_import1_proto_depIdxs,
		MessageInfos:      file_import1_proto_msgTypes,
	}.Build()
	File_import1_proto = out.File
	file_import1_proto_rawDesc = nil
	file_import1_proto_goTypes = nil
	file_import1_proto_depIdxs = nil
}
